//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTLAR
    {
        public int NOTID { get; set; }
        public byte DERSID { get; set; }
        public int OGRID { get; set; }
        public byte SINAV1 { get; set; }
        public byte SINAV2 { get; set; }
        public byte PROJE { get; set; }
        public decimal ORTALAMA { get; set; }
        public bool DURUM { get; set; }
    
        public virtual TBLDERSLER TBLDERSLER { get; set; }
        public virtual TBLOGRENCILER TBLOGRENCILER { get; set; }
    }
}
